MAPPING_DICT  = {
    "smart_1_normalized":"smart_1_normalized",
    "smart_1_raw":"smart_1_raw",
    "smart_2_normalized":"smart_2_normalized",
    "smart_2_raw":"smart_2_raw",
    "smart_3_normalized":"smart_3_normalized",
    "smart_3_raw":"smart_3_raw",
    "smart_4_normalized":"smart_4_normalized",
    "smart_4_raw":"smart_4_raw",
    "smart_5_normalized":"smart_5_normalized",
    "smart_5_raw":"smart_5_raw",
    "smart_7_normalized":"smart_7_normalized",
    "smart_7_raw":"smart_7_raw",
    "smart_8_normalized":"smart_8_normalized",
    "smart_8_raw":"smart_8_raw",
    "smart_9_normalized":"smart_9_normalized",
    "Power On Hours":"smart_9_raw",
    "smart_10_normalized":"smart_10_normalized",
    "smart_10_raw":"smart_10_raw",
    "smart_12_normalized":"smart_12_normalized",
    "Power Cycles":"smart_12_raw",
    "smart_183_normalized":"smart_183_normalized",
    "smart_183_raw":"smart_183_raw",
    "smart_184_normalized":"smart_184_normalized",
    "smart_184_raw":"smart_184_raw",
    "smart_187_normalized":"smart_187_normalized",
    "smart_187_raw":"smart_187_raw",
    "smart_188_normalized":"smart_188_normalized",
    "smart_188_raw":"smart_188_raw",
    "smart_189_normalized":"smart_189_normalized",
    "smart_189_raw":"smart_189_raw",
    "smart_190_normalized":"smart_190_normalized",
    "smart_190_raw":"smart_190_raw",
    "smart_191_normalized":"smart_191_normalized",
    "smart_191_raw":"smart_191_raw",
    "smart_192_normalized":"smart_192_normalized",
    "Unsafe Shutdowns":"smart_192_raw",
    "smart_193_normalized":"smart_193_normalized",
    "smart_193_raw":"smart_193_raw",
    "smart_194_normalized":"smart_194_normalized",
    "Temperature":"smart_194_raw",
    "smart_196_normalized":"smart_196_normalized",
    "smart_196_raw":"smart_196_raw",
    "smart_197_normalized":"smart_197_normalized",
    "smart_197_raw":"smart_197_raw",
    "smart_198_normalized":"smart_198_normalized",
    "smart_198_raw":"smart_198_raw",
    "smart_199_normalized":"smart_199_normalized",
    "smart_199_raw":"smart_199_raw",
    "smart_240_normalized":"smart_240_normalized",
    "smart_240_raw":"smart_240_raw",
    "smart_241_normalized":"smart_241_normalized",
    "Host Write Commands":"smart_241_raw",
    "smart_242_normalized":"smart_242_normalized",
    "Host Read Commands":"smart_242_raw",
}

LIST_SMART = [
    "smart_1_normalized",
    "smart_1_raw",
    "smart_2_normalized",
    "smart_2_raw",
    "smart_3_normalized",
    "smart_3_raw",
    "smart_4_normalized",
    "smart_4_raw",
    "smart_5_normalized",
    "smart_5_raw",
    "smart_7_normalized",
    "smart_7_raw",
    "smart_8_normalized",
    "smart_8_raw",
    "smart_9_normalized",
    "smart_9_raw",
    "smart_10_normalized",
    "smart_10_raw",
    "smart_12_normalized",
    "smart_12_raw",
    "smart_183_normalized",
    "smart_183_raw",
    "smart_184_normalized",
    "smart_184_raw",
    "smart_187_normalized",
    "smart_187_raw",
    "smart_188_normalized",
    "smart_188_raw",
    "smart_189_normalized",
    "smart_189_raw",
    "smart_190_normalized",
    "smart_190_raw",
    "smart_191_normalized",
    "smart_191_raw",
    "smart_192_normalized",
    "smart_192_raw",
    "smart_193_normalized",
    "smart_193_raw",
    "smart_194_normalized",
    "smart_194_raw",
    "smart_196_normalized",
    "smart_196_raw",
    "smart_197_normalized",
    "smart_197_raw",
    "smart_198_normalized",
    "smart_198_raw",
    "smart_199_normalized",
    "smart_199_raw",
    "smart_240_normalized",
    "smart_240_raw",
    "smart_241_normalized",
    "smart_241_raw",
    "smart_242_normalized",
    "smart_242_raw",
]


SMART_MAP_STANDARD = {
    "smart_9_raw": "power_on_hours",
    "smart_12_raw": "power_cycle",
    "smart_192_raw": "unsafe_shutdowns",
    "smart_194_raw": "temperature",
    "smart_1_raw": "read_error_rate"
}

SMART_IMPORTANT_TABLE_FIELD = {
    "power_on_hours": "power_on_hours",
    "power_cycle": "power_cycle",
    "unsafe_shutdowns": "unsafe_shutdowns",
    "temperature": "temperature",
    "read_error_rate": "read_error_rate",
    "serial_number": "serial_number",
    "date": "date",
    "class_prediction": "class_prediction",
}